source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CAFFImageSwitch_Example', :exclusive => true do
  pod "CAFFImageSwitch", :path => "../"
end

target 'CAFFImageSwitch_Tests', :exclusive => true do
  pod "CAFFImageSwitch", :path => "../"

  
end
